#!/usr/bin/python
from transformers import AutoTokenizer
import argparse

parser = argparse.ArgumentParser(description="DeepSeek v2 tokenizer")

parser.add_argument("inputs", type=str, default="", help="输入")

args = parser.parse_args()
inputs = args.inputs

# 加载 DeepSeek-V2 的分词器
tokenizer = AutoTokenizer.from_pretrained("./assets/deepseek_v2_tokenizer/deepseek_v2_tokenizer/")

encode = tokenizer.encode(inputs)
print(f"- encode : \n{encode}")

decode = [tokenizer.decode(ei) for ei in encode]

print(f"- decode : \n{decode}")

